# -*- coding: utf-8 -*-
"""RAG_QA_Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kmLD7sqqOVa3ZwKR4KKPk38lKejL-Y6p
"""

!pip install -q beautifulsoup4 requests pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd
from tqdm import tqdm

#  لینک‌هایی که مشخص شد توسط دستیاران
URLS = [
    "https://www.britannica.com/place/France/Land",
    "https://www.britannica.com/place/France/The-Hercynian-massifs",
    "https://www.britannica.com/place/France/The-great-lowlands",
    "https://www.britannica.com/place/France/The-younger-mountains-and-adjacent-plains",
    "https://www.britannica.com/place/France/Drainage",
    "https://www.britannica.com/place/France/Soils",
    "https://www.britannica.com/place/France/Climate",
    "https://www.britannica.com/place/France/Plant-and-animal-life",
]

def scrape_page(url):
    res = requests.get(url)
    soup = BeautifulSoup(res.text, "html.parser")

    paragraphs = soup.find_all("p")
    text = "\n".join(p.get_text(strip=True) for p in paragraphs)

    title = soup.title.get_text() if soup.title else "No Title"
    return {"url": url, "title": title, "content": text}

#  استخراج متن صفحات
data = [scrape_page(url) for url in tqdm(URLS)]

#  ذخیره در دیتافریم
df = pd.DataFrame(data)
df.to_csv("france_land_sections.csv", index=False)

print(" استخراج و ذخیره داده‌ها کامل شد.")
df.head()

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['title'].value_counts()
    for x_label, grp in _df_3.groupby('url')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('url')
_ = plt.ylabel('title')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['content'].value_counts()
    for x_label, grp in _df_4.groupby('title')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('title')
_ = plt.ylabel('content')

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('title').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('url').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

!pip install -q sentence-transformers nltk

# پاک‌سازی و دانلود مجدد دیتای nltk
import nltk
import shutil
import os

# حذف دیتای قبلی در صورت وجود
shutil.rmtree('/root/nltk_data', ignore_errors=True)
os.makedirs('/root/nltk_data', exist_ok=True)

# دانلود punkt به مسیر درست
nltk.download('punkt', download_dir='/root/nltk_data')

# اطمینان از اینکه nltk از مسیر صحیح استفاده کنه
nltk.data.path.clear()
nltk.data.path.append('/root/nltk_data')

from sentence_transformers import SentenceTransformer
import nltk
import pandas as pd
import numpy as np
import re
import pickle
from tqdm import tqdm

nltk.download('punkt')

#  مدل embedding
model = SentenceTransformer("all-MiniLM-L6-v2")

#  خواندن فایل
df = pd.read_csv("france_land_sections.csv")

#  تابع پاک‌سازی متن
def clean_text(text):
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()
    return text

# #  تابع chunk کردن
# def chunk_text(text, chunk_size=100, overlap=20):
#     sentences = nltk.sent_tokenize(text)
#     words = " ".join(sentences).split()
#     chunks = []

#     for i in range(0, len(words), chunk_size - overlap):
#         chunk = " ".join(words[i:i+chunk_size])
#         if len(chunk.split()) > 10:  # حداقل طول
#             chunks.append(chunk)
#     return chunks

import re

def chunk_text(text, chunk_size=100, overlap=20):
    # شبیه سازی ساده‌ای از جمله‌بندی، بدون nltk
    sentences = re.split(r'(?<=[.!?]) +', text)
    words = " ".join(sentences).split()
    chunks = []

    for i in range(0, len(words), chunk_size - overlap):
        chunk = " ".join(words[i:i+chunk_size])
        if len(chunk.split()) > 10:
            chunks.append(chunk)
    return chunks

#  ساخت embedding برای همه‌ی chunkها
all_chunks = []
all_embeddings = []
all_metadata = []

for idx, row in tqdm(df.iterrows(), total=len(df)):
    cleaned = clean_text(row["content"])
    chunks = chunk_text(cleaned)

    embeddings = model.encode(chunks, show_progress_bar=False)

    all_chunks.extend(chunks)
    all_embeddings.extend(embeddings)
    all_metadata.extend([{"title": row["title"], "url": row["url"]}] * len(chunks))

#  ذخیره در یک فایل پیکل
with open("embedding_store.pkl", "wb") as f:
    pickle.dump({
        "chunks": all_chunks,
        "embeddings": np.array(all_embeddings),
        "metadata": all_metadata
    }, f)

print(" Embedding Store آماده شد و در فایل embedding_store.pkl ذخیره شد.")

!pip install -q faiss-cpu

import pickle
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer

#  بارگذاری embedding‌ها
with open("embedding_store.pkl", "rb") as f:
    store = pickle.load(f)

embeddings = np.array(store["embeddings"]).astype("float32")  # FAISS نیاز به float32 داره
chunks = store["chunks"]
metadata = store["metadata"]

#  مدل encoder
model = SentenceTransformer("all-MiniLM-L6-v2")

#  ساخت ایندکس FAISS (cosine similarity از طریق index flat L2)
dimension = embeddings.shape[1]
index = faiss.IndexFlatIP(dimension)

# نرمال‌سازی برای cosine similarity
faiss.normalize_L2(embeddings)
index.add(embeddings)

def retrieve_top_k(query, k=5):
    # 1. تبدیل query به embedding
    query_embedding = model.encode([query]).astype("float32")
    faiss.normalize_L2(query_embedding)

    # 2. جستجوی FAISS
    distances, indices = index.search(query_embedding, k)

    # 3. بازگرداندن نتایج
    results = []
    for i in indices[0]:
        results.append({
            "chunk": chunks[i],
            "metadata": metadata[i]
        })
    return results

results = retrieve_top_k("What kind of climate does France have?", k=3)

for i, res in enumerate(results):
    print(f"\n--- Result {i+1} ---")
    print(" Title:", res["metadata"]["title"])
    print(" Chunk:", res["chunk"][:300], "...")

"""# **Fast API**"""

!pip install -q fastapi nest_asyncio uvicorn pyngrok

!ngrok config add-authtoken 2xxCCTlrJIrUqOiKiSMqyZEOWQb_7x6Ko9graZUdeEBhDNeKk

"""### **ALL in One**"""

# ------------------------- نصب‌ها (فقط بار اول لازم است) -------------------------
!pip install -q fastapi nest_asyncio pyngrok uvicorn openai

# ------------------------- ایمپورت‌ها -------------------------
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List
import nest_asyncio
from pyngrok import ngrok
import uvicorn
import threading
import requests

# ------------------------- تنظیمات -------------------------
nest_asyncio.apply()
app = FastAPI()

TOGETHER_API_KEY = "a645ea5d637a4b47630140c2eb3579f8d2b3761155813a3a2761fb669098c831"  #  با توکن واقعی خودت جایگزین کن

# ------------------------- توابع اصلی -------------------------

def retrieve_top_k(query, k=5):
    import pickle
    import numpy as np
    from sentence_transformers import SentenceTransformer
    import faiss

    # بارگذاری داده‌ها
    with open("embedding_store.pkl", "rb") as f:
        store = pickle.load(f)

    model = SentenceTransformer("all-MiniLM-L6-v2")
    embeddings = np.array(store["embeddings"]).astype("float32")
    chunks = store["chunks"]
    metadata = store["metadata"]

    # ساخت ایندکس FAISS
    faiss.normalize_L2(embeddings)
    index = faiss.IndexFlatIP(embeddings.shape[1])
    index.add(embeddings)

    query_emb = model.encode([query]).astype("float32")
    faiss.normalize_L2(query_emb)

    D, I = index.search(query_emb, k)
    return [{"chunk": chunks[i], "metadata": metadata[i]} for i in I[0]]


def generate_answer_with_togetherai(query, k=5):
    context_chunks = retrieve_top_k(query, k)
    context = "\n\n".join([c["chunk"] for c in context_chunks])

    prompt = f"""You are an expert assistant. Use the following context to answer the question truthfully and concisely.

Context:
{context}

Question:
{query}

Answer:"""

    headers = {
        "Authorization": f"Bearer {TOGETHER_API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        # "model": "meta-llama/Llama-3-8B-Instruct",  # یا مدل دلخواه مثل deepseek-ai/DeepSeek...
        "model": "mistralai/Mistral-7B-Instruct-v0.1",
        "prompt": prompt,
        "max_tokens": 256,
        "temperature": 0.7,
        "top_p": 0.9
    }

    res = requests.post("https://api.together.xyz/v1/completions", headers=headers, json=payload)

    if res.status_code != 200:
        raise Exception(f"LLM API Error {res.status_code}: {res.text}")

    return res.json()["choices"][0]["text"].strip()

# ------------------------- مدل‌های ورودی/خروجی -------------------------
class RetrieveRequest(BaseModel):
    query: str
    k: int = 5

class RetrievedChunk(BaseModel):
    chunk: str
    metadata: dict

class GenerateRequest(BaseModel):
    query: str
    k: int = 5

class GenerateResponse(BaseModel):
    answer: str

# ------------------------- مسیرهای API -------------------------
@app.post("/retrieve", response_model=List[RetrievedChunk])
def retrieve_chunks(request: RetrieveRequest):
    try:
        return retrieve_top_k(request.query, request.k)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/generate", response_model=GenerateResponse)
def generate_endpoint(request: GenerateRequest):
    try:
        answer = generate_answer_with_togetherai(request.query, request.k)
        return {"answer": answer}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ------------------------- اجرا با ngrok و threading -------------------------
public_url = ngrok.connect(8000)
print("FastAPI is running at:", public_url)

def run_app():
    uvicorn.run(app, port=8000)

thread = threading.Thread(target=run_app)
thread.start()

from pyngrok import ngrok

# بستن همه‌ی تونل‌های باز
ngrok.kill()

import requests

# url = "<NGROK_URL>/retrieve"  # لینک چاپ‌شده بالا
url = "https://3bef-34-41-234-225.ngrok-free.app/"

endpoint = f"{url}/retrieve"

query_data = {
    "query": "What are the mountain regions in France?",
    "k": 3
}

response = requests.post(endpoint, json=query_data)
print(response.status_code)
try:
    print(response.json())
except Exception as e:
    print("Response was not JSON:", response.text)

import requests

url = "https://3bef-34-41-234-225.ngrok-free.app/"  #  آدرس جدید
endpoint = f"{url}/generate"

query_data = {
    "query": "What are the major mountain ranges in France?",
    "k": 3
}

response = requests.post(endpoint, json=query_data)
print(response.status_code)
print(response.json())

"""بر اساس متن‌های استخراج‌شده از بریتانیکا که شامل صفحات زیر بودن :   

The Hercynian massifs (https://www.britannica.com/place/France/The-Hercynian-massifs)

The-younger-mountains (https://www.britannica.com/place/France/The-younger-mountains-and-adjacent-plains)

Drainage (https://www.britannica.com/place/France/Drainage)

نام برده‌شده ها :

**French Alps → بله در داده هست ✅**

**Pyrenees → بله در داده هست ✅**

**Massif Central → بله (جزو Hercynian Massifs) ✅**

 پس مدل از داده‌ی واقعی استخراج‌شده و توهم هالوسینیشن هم نداره.

# **Streamlit + FastAPI**
"""

!pip install -q streamlit
!pip install -q pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import requests
# import pickle
# import numpy as np
# from sentence_transformers import SentenceTransformer
# import faiss
# 
# # ------------------ بارگذاری داده ------------------
# with open("embedding_store.pkl", "rb") as f:
#     store = pickle.load(f)
# 
# chunks = store["chunks"]
# metadata = store["metadata"]
# embeddings = np.array(store["embeddings"]).astype("float32")
# model = SentenceTransformer("all-MiniLM-L6-v2")
# 
# # ساخت ایندکس FAISS
# faiss.normalize_L2(embeddings)
# index = faiss.IndexFlatIP(embeddings.shape[1])
# index.add(embeddings)
# 
# # ------------------ تابع بازیابی + شباهت ------------------
# def retrieve_top_k(query, k=3):
#     query_emb = model.encode([query]).astype("float32")
#     faiss.normalize_L2(query_emb)
#     scores, indices = index.search(query_emb, k)
#     return [
#         {
#             "chunk": chunks[i],
#             "metadata": metadata[i],
#             "score": round(float(scores[0][j]), 4)
#         }
#         for j, i in enumerate(indices[0])
#     ]
# 
# # ------------------ تابع تولید پاسخ ------------------
# TOGETHER_API_KEY = "a645ea5d637a4b47630140c2eb3579f8d2b3761155813a3a2761fb669098c831"  #  توکن خودت
# 
# def generate_answer(query, k=3):
#     context_chunks = retrieve_top_k(query, k)
#     context = "\n\n".join([c["chunk"] for c in context_chunks])
# 
#     prompt = f"""You are a helpful assistant answering based on provided context.
# 
# Context:
# {context}
# 
# Question:
# {query}
# 
# Answer:"""
# 
#     headers = {
#         "Authorization": f"Bearer {TOGETHER_API_KEY}",
#         "Content-Type": "application/json"
#     }
# 
#     payload = {
#         "model": "mistralai/Mistral-7B-Instruct-v0.1",
#         "prompt": prompt,
#         "max_tokens": 256,
#         "temperature": 0.7,
#         "top_p": 0.9
#     }
# 
#     res = requests.post("https://api.together.xyz/v1/completions", headers=headers, json=payload)
#     if res.status_code != 200:
#         return f"❌ API Error {res.status_code}: {res.text}", context_chunks
#     return res.json()["choices"][0]["text"].strip(), context_chunks
# 
# # ------------------ UI Streamlit ------------------
# st.set_page_config(page_title="France RAG Assistant", layout="centered")
# st.title("🇫🇷 Amin.K + Radmehr.A - QA Assistant (RAG)")
# st.markdown("Ask anything about France’s geography (🗻 Land, 🌦️ Climate, 🌊 Rivers...)")
# 
# query = st.text_input("🔎 Enter your question")
# top_k = st.slider("📊 Number of chunks to retrieve", 1, 10, 3)
# 
# if st.button("🧠 Generate Answer"):
#     if not query.strip():
#         st.warning("Please enter a valid question.")
#     else:
#         with st.spinner("Thinking..."):
#             answer, retrieved = generate_answer(query, top_k)
#             st.success("✅ Answer:")
#             st.markdown(f"**{answer}**")
# 
#             st.markdown("---")
#             st.subheader("📄 Retrieved Chunks with Similarity")
#             for i, chunk in enumerate(retrieved):
#                 st.markdown(f"**Chunk {i+1} (Score: {chunk['score']})**")
#                 st.code(chunk["chunk"][:500] + "...")
#                 st.caption(f"[{chunk['metadata']['title']}]({chunk['metadata']['url']})")
#

!pip install -q streamlit pyngrok
from pyngrok import ngrok
ngrok.kill()

# اجرای استریم‌لیت
!nohup streamlit run app.py &

# # ایجاد تونل
# public_url = ngrok.connect(8501)
# print("🌍 Streamlit UI is running at:", public_url)

from pyngrok import ngrok
ngrok.kill()

!pkill streamlit || echo "streamlit not running"

# اجرای Streamlit در بک‌گراند واقعی (با log)
!nohup streamlit run app.py > streamlit.log 2>&1 &

public_url = ngrok.connect(8501, "http")
print("🌍 Your Streamlit app is live at:", public_url)

"""# Temp -------------------------------------

استخراج و ذخیره اولیه داده‌ها
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
from tqdm import tqdm
from datetime import datetime

# URLs of Britannica Land sections
URLS = [
    "https://www.britannica.com/place/France/Land",
    "https://www.britannica.com/place/France/The-Hercynian-massifs",
    "https://www.britannica.com/place/France/The-great-lowlands",
    "https://www.britannica.com/place/France/The-younger-mountains-and-adjacent-plains",
    "https://www.britannica.com/place/France/Drainage",
    "https://www.britannica.com/place/France/Soils",
    "https://www.britannica.com/place/France/Climate",
    "https://www.britannica.com/place/France/Plant-and-animal-life",
]

def scrape_page(url):
    res = requests.get(url)
    soup = BeautifulSoup(res.text, "html.parser")
    paragraphs = soup.find_all("p")
    text = "\n".join(p.get_text(strip=True) for p in paragraphs)
    title = soup.title.get_text() if soup.title else "No Title"
    date_scraped = datetime.utcnow().isoformat()
    return {
        "url": url,
        "title": title,
        "content": text,
        "category": "France-Geography",
        "date": date_scraped
    }

# Scrape and save to CSV
data = [scrape_page(url) for url in tqdm(URLS)]
df = pd.DataFrame(data)
df.to_csv("france_land_sections.csv", index=False)
print("✅ Saved to france_land_sections.csv")

"""پاک سازی و تعبیه و چانک و متادیتا"""

import nltk
import random

import string
from nltk.tokenize import word_tokenize
from collections import defaultdict, Counter
import re
import math
from nltk.corpus import stopwords

# !pip install datasets hazm
from datasets import load_dataset
# from hazm import Normalizer, word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

# پاکسازی کامل کش‌های خراب
nltk.download('popular')
nltk.download('all')

import pandas as pd
import numpy as np
import re
import nltk
import pickle
from tqdm import tqdm
from sentence_transformers import SentenceTransformer

nltk.download("punkt")

# Load CSV
df = pd.read_csv("france_land_sections.csv")

# Clean text
def clean_text(text):
    text = text.encode("utf-8", "ignore").decode() # ✅ fix encoding
    text = re.sub(r'\s+', ' ', text)  # ✅ normalize spaces
    text = re.sub(r'\[[^\]]*\]', '', text)   # ✅ strip citation noise like [1] => citation
    return text.strip()

# Chunk text (fixed-length with overlap)
def chunk_text(text, chunk_size=100, overlap=20):
    sentences = nltk.sent_tokenize(text)
    words = " ".join(sentences).split()
    chunks = []
    for i in range(0, len(words), chunk_size - overlap):
        chunk = " ".join(words[i:i+chunk_size])
        if len(chunk.split()) > 10:
            chunks.append(chunk)
    return chunks

# Embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

all_chunks = []
all_embeddings = []
all_metadata = []

for idx, row in tqdm(df.iterrows(), total=len(df)):
    cleaned = clean_text(row["content"])
    chunks = chunk_text(cleaned, chunk_size=100, overlap=20)
    embeddings = model.encode(chunks, show_progress_bar=False)

    all_chunks.extend(chunks)
    all_embeddings.extend(embeddings)
    all_metadata.extend([{
        "title": row["title"],
        "url": row["url"],
        "category": row["category"],
        "date": row["date"],
        "source": "Britannica"
    }] * len(chunks))

# Save to pickle
with open("embedding_store.pkl", "wb") as f:
    pickle.dump({
        "chunks": all_chunks,
        "embeddings": np.array(all_embeddings),
        "metadata": all_metadata
    }, f)

print("✅ embedding_store.pkl created successfully.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import requests
# import pickle
# import numpy as np
# from sentence_transformers import SentenceTransformer
# import faiss
# import plotly.express as px
# import os
# # ----------------- بارگذاری داده‌ها -----------------
# with open("embedding_store.pkl", "rb") as f:
#     store = pickle.load(f)
# 
# chunks = store["chunks"]
# metadata = store["metadata"]
# embeddings = np.array(store["embeddings"]).astype("float32")
# 
# # اگر user_additions وجود دارد، اضافه کن
# if os.path.exists("user_additions.pkl"):
#     with open("user_additions.pkl", "rb") as f:
#         user_store = pickle.load(f)
#     chunks += user_store["chunks"]
#     metadata += user_store["metadata"]
#     user_embeddings = np.array(user_store["embeddings"]).astype("float32")
#     embeddings = np.concatenate([embeddings, user_embeddings], axis=0)
# 
# 
# model = SentenceTransformer("all-MiniLM-L6-v2")
# # model = SentenceTransformer("togethercomputer/m2-bert-80M-8k-retrieval")
# 
# #Vector Retrieval
# faiss.normalize_L2(embeddings)
# index = faiss.IndexFlatIP(embeddings.shape[1])
# index.add(embeddings)
# 
# # ----------------- توابع اصلی -----------------
# # def retrieve_top_k(query, k=3):
# #     query_emb = model.encode([query]).astype("float32")
# #     faiss.normalize_L2(query_emb)
# #     scores, indices = index.search(query_emb, k)
# #     return [
# #         {
# #             "chunk": chunks[i],
# #             "metadata": metadata[i],
# #             "score": round(float(scores[0][j]), 4)
# #         }
# #         for j, i in enumerate(indices[0])
# #     ]
# 
# def retrieve_top_k(query, k=3, filter_by=None):
#     """
#     query: سوال کاربر
#     k: تعداد نتایج برتر
#     filter_by: دیکشنری فیلتر مثل {'category': 'France-Geography'}
#     """
#     # فیلتر کردن داده‌ها بر اساس متادیتا
#     filtered_chunks = []
#     filtered_metadata = []
#     filtered_embeddings = []
# 
#     for i, meta in enumerate(metadata):
#         if filter_by is None or all(meta.get(key) == val for key, val in filter_by.items()):
#             filtered_chunks.append(chunks[i])
#             filtered_metadata.append(meta)
#             filtered_embeddings.append(embeddings[i])
# 
#     if not filtered_chunks:
#         return []
# 
#     index_temp = faiss.IndexFlatIP(embeddings.shape[1])
#     vectors = np.array(filtered_embeddings).astype("float32")
#     faiss.normalize_L2(vectors)
#     index_temp.add(vectors)
# 
#     # Embedding سوال کاربر و جستجو
#     query_emb = model.encode([query]).astype("float32")
#     faiss.normalize_L2(query_emb)
#     scores, indices = index_temp.search(query_emb, k)
# 
#     return [
#         {
#             "chunk": filtered_chunks[i],
#             "metadata": filtered_metadata[i],
#             "score": round(float(scores[0][j]), 4)
#         }
#         for j, i in enumerate(indices[0])
#     ]
# 
# TOGETHER_API_KEY = "a645ea5d637a4b47630140c2eb3579f8d2b3761155813a3a2761fb669098c831"  #  توکن خودت
# 
# def generate_answer(query, retrieved, model_name, temperature, top_p, max_tokens):
#     context = "\n\n".join([c["chunk"] for c in retrieved])
# 
#     prompt = f"""You are a helpful assistant answering based on provided context.
# 
# Context:
# {context}
# 
# Question:
# {query}
# 
# Answer:"""
# 
#     headers = {
#         "Authorization": f"Bearer {TOGETHER_API_KEY}",
#         "Content-Type": "application/json"
#     }
# 
#     payload = {
#         "model": model_name,
#         "prompt": prompt,
#         "max_tokens": max_tokens,
#         "temperature": temperature,
#         "top_p": top_p
#     }
# 
#     res = requests.post("https://api.together.xyz/v1/completions", headers=headers, json=payload)
# 
#     if res.status_code != 200:
#         return f"❌ API Error {res.status_code}: {res.text}", prompt
# 
#     answer = res.json()["choices"][0]["text"].strip()
#     return answer, prompt
# 
# # ----------------- Streamlit UI -----------------
# st.set_page_config("📘 France RAG Assistant", layout="wide")
# 
# st.markdown("<h1 style='color:#0f62fe;'>🇫🇷 RAK QA Assistant</h1>", unsafe_allow_html=True)
# st.write("Ask questions about France's **Land, Mountains, Rivers, Climate** etc. Powered by RAG and LLM.")
# 
# col1, col2 = st.columns([3, 1])
# with col1:
#     query = st.text_input("🧠 What do you want to know?", placeholder="E.g. What are the main mountains in France?")
# with col2:
#     top_k = st.slider("🔍 Top-K Chunks", 1, 10, 3)
# 
# # Parameters section
# with st.expander("⚙️ Model & Generation Settings"):
#     model_name = st.selectbox("LLM Model", ["mistralai/Mistral-7B-Instruct-v0.1",
#                                             "deepseek-ai/DeepSeek-Coder-6.7B-Instruct",
#                                             "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free",
#                                             "deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free"])
#     temperature = st.slider("Temperature", 0.0, 1.5, 0.7)
#     top_p = st.slider("Top-p", 0.0, 1.0, 0.9)
#     max_tokens = st.slider("Max Tokens", 64, 1024, 256)
# 
# with st.expander("📂 Metadata Filters"):
#     category_options = sorted(set(
#         m["category"] for m in metadata if m.get("category") not in [None, ""]
#     ))
#     source_options = sorted(set(
#         m["source"] for m in metadata if m.get("source") not in [None, ""]
#     ))
# 
#     category_options = ["All"] + category_options
#     source_options = ["All"] + source_options
# 
#     selected_category = st.selectbox("Filter by Category", category_options)
#     selected_source = st.selectbox("Filter by Source", source_options)
# 
#     filters = {}
#     if selected_category != "All":
#         filters["category"] = selected_category
#     if selected_source != "All":
#         filters["source"] = selected_source
# 
# 
# retrieved = retrieve_top_k(query, top_k, filter_by=filters)
# 
# if st.button("🚀 Generate Answer"):
#     if not query.strip():
#         st.warning("Please enter a question.")
#     else:
#         with st.spinner("🔄 Retrieving context and generating response..."):
#             retrieved = retrieve_top_k(query, top_k)
#             answer, prompt_used = generate_answer(query, retrieved, model_name, temperature, top_p, max_tokens)
# 
#         st.success("✅ Final Answer:")
#         # st.markdown(f"**{answer}**")
#         st.code(f"**{answer}**", language="markdown")
#         st.caption(f"📝 Word count: {len(answer.split())}")
#         st.download_button("📥 Download Answer", data=answer, file_name="answer.txt")
# 
#         st.markdown("---")
#         st.subheader("📄 Retrieved Chunks and Similarity")
# 
#         for i, c in enumerate(retrieved):
#             st.markdown(f"**Chunk {i+1} — Score: `{c['score']}`**")
#             st.code(c["chunk"][:500] + "...")
#             st.markdown(f"🔗 [{c['metadata']['title']}]({c['metadata']['url']})")
# 
#         st.markdown("### 📊 Chunk Similarity Chart")
#         fig = px.bar(
#             x=[c["score"] for c in retrieved],
#             y=[f"Chunk {i+1}" for i in range(len(retrieved))],
#             orientation='h',
#             labels={'x': 'Similarity Score', 'y': 'Chunk'},
#             color=[c["score"] for c in retrieved],
#             color_continuous_scale='blues'
#         )
#         st.plotly_chart(fig, use_container_width=True)
# 
#         st.markdown("---")
#         with st.expander("🧾 View Prompt Sent to LLM"):
#             st.code(prompt_used)
# 
#         st.markdown("💬 Was this answer useful?")
#         cols = st.columns([1, 1])
#         with cols[0]:
#             if st.button("👍 Yes"):
#                 st.success("Thanks for your feedback!")
#         with cols[1]:
#             if st.button("👎 No"):
#                 st.info("We'll try to improve.")
# 
# 
# with st.expander("ℹ️ Retrieval Strategy Explanation"):
#     st.markdown("""
#     **Retrieval Approach Used:**
#     - ✅ Cosine Similarity over Sentence Embeddings
#     - ✅ Optional Metadata Filtering (category, source, etc.)
#     - ✅ Top-K configurable
# 
#     **Why this works well:**
#     - Cosine similarity finds chunks that are semantically close to your query.
#     - Metadata filtering improves *precision* by narrowing context to relevant sections.
#     - Top-K tuning allows control over *recall* (bigger K → more results).
# 
#     This balances precision and recall effectively by combining dense vector search with symbolic filters.
#     """)
# 
# 
# with st.expander("➕ Add New Data (URL or Text)"):
#     mode = st.radio("Input type:", ["🧭 URL", "📝 Raw Text"])
#     new_title = st.text_input("Title")
#     new_data = st.text_area("Paste your URL or text here")
# 
#     if st.button("📥 Add to Dataset"):
#         if not new_title or not new_data:
#             st.warning("Both title and data are required.")
#         else:
#             if mode == "🧭 URL":
#                 import requests
#                 from bs4 import BeautifulSoup
#                 try:
#                     res = requests.get(new_data)
#                     soup = BeautifulSoup(res.text, "html.parser")
#                     paragraphs = soup.find_all("p")
#                     new_content = "\n".join(p.get_text(strip=True) for p in paragraphs)
#                 except Exception as e:
#                     st.error(f"Failed to fetch URL: {e}")
#                     new_content = ""
#             else:
#                 new_content = new_data
# 
#             if new_content.strip():
#                 # Chunk + Embed
#                 from sentence_transformers import SentenceTransformer
#                 import faiss
#                 import numpy as np
#                 import nltk
#                 nltk.download('punkt')
#                 from nltk.tokenize import sent_tokenize
# 
#                 def chunk_text(text, size=100, overlap=20):
#                     words = text.split()
#                     chunks = []
#                     for i in range(0, len(words), size - overlap):
#                         chunk = " ".join(words[i:i+size])
#                         if len(chunk.split()) > 10:
#                             chunks.append(chunk)
#                     return chunks
# 
#                 new_chunks = chunk_text(new_content)
#                 new_embeddings = model.encode(new_chunks).astype("float32")
#                 faiss.normalize_L2(new_embeddings)
#                 index.add(new_embeddings)
# 
#                 chunks.extend(new_chunks)
#                 metadata.extend([{"title": new_title, "url": new_data}] * len(new_chunks))
# 
#                 user_path = "user_additions.pkl"
# 
#                 if os.path.exists(user_path):
#                     with open(user_path, "rb") as f:
#                         existing = pickle.load(f)
#                     user_chunks = existing["chunks"] + new_chunks
#                     user_metadata = existing["metadata"] + [{"title": new_title, "url": new_data}] * len(new_chunks)
#                     user_embeddings = np.concatenate([existing["embeddings"], new_embeddings], axis=0)
#                 else:
#                     user_chunks = new_chunks
#                     user_metadata = [{"title": new_title, "url": new_data}] * len(new_chunks)
#                     user_embeddings = new_embeddings
# 
#                 with open(user_path, "wb") as f:
#                     pickle.dump({
#                         "chunks": user_chunks,
#                         "embeddings": user_embeddings,
#                         "metadata": user_metadata
#                     }, f)
# 
#                 # # ذخیره به embedding_store.pkl
#                 # import pickle
#                 # with open("embedding_store.pkl", "wb") as f:
#                 #     pickle.dump({
#                 #         "chunks": chunks,
#                 #         "embeddings": index.reconstruct_n(0, index.ntotal),  # بازسازی همه بردارها
#                 #         "metadata": metadata
#                 #     }, f)
# 
#                 st.success(f"{len(new_chunks)} chunks added successfully ✅")
# 
# # with st.expander("📂 View User-Added Data"):
# #     import os
# #     if os.path.exists("user_additions.pkl"):
# #         with open("user_additions.pkl", "rb") as f:
# #             udata = pickle.load(f)
# 
# #         st.markdown(f"**Total Chunks:** {len(udata['chunks'])}")
# #         for i, (chunk, meta) in enumerate(zip(udata["chunks"], udata["metadata"])):
# #             with st.expander(f"🧩 Chunk {i+1} — {meta['title']}"):
# #                 st.code(chunk[:500] + "...")
# #                 st.markdown(f"🔗 [Source]({meta['url']})")
# #     else:
# #         st.info("No user-added data yet.")
# 
# 
# with st.expander("📂 View & Manage User-Added Data"):
#     import os
#     user_path = "user_additions.pkl"
# 
#     if os.path.exists(user_path):
#         with open(user_path, "rb") as f:
#             udata = pickle.load(f)
# 
#         st.markdown(f"**🧠 Total Chunks:** {len(udata['chunks'])}")
# 
#         for i, (chunk, meta) in enumerate(zip(udata["chunks"], udata["metadata"])):
#             st.markdown(f"---\n### 🧩 Chunk {i+1} — {meta['title']}")
#             st.code(chunk[:500] + "...")
#             st.markdown(f"🔗 [Source]({meta['url']})")
# 
#             if st.button(f"❌ Delete Chunk {i+1}", key=f"del_{i}"):
#                 udata["chunks"].pop(i)
#                 udata["metadata"].pop(i)
#                 udata["embeddings"] = np.delete(udata["embeddings"], i, axis=0)
# 
#                 with open(user_path, "wb") as f:
#                     pickle.dump(udata, f)
# 
#                 st.experimental_rerun()
#     else:
#         st.info("No user-added data yet.")
# 
#

from pyngrok import ngrok
ngrok.kill()
!pkill streamlit || echo "streamlit not running"

# اجرای Streamlit در بک‌گراند واقعی (با log)
!nohup streamlit run app.py > streamlit.log 2>&1 &

public_url = ngrok.connect(8501, "http")
print("🌍 Your Streamlit app is live at:", public_url)